### PR TITLE
:broom: Use newest magetasks

### LINKED ISSUE #243: `ARTIFACTS` should contain only report files and clean shouldn't remove already collected artifacts
The following change made a side effect that `./mage clean` removes all artifacts, which is unfortunate in testing and in release jobs.

Also, it archives all binaries for every PR which is undesirable.

https://github.com/wavesoftware/go-magetasks/blame/685c1062a6dd0789454d964da18946aa3669b026/pkg/files/dirs.go#L23-L26

/kind bug

### PR DESCRIPTION
**Pull request by cardil**
# Changes

- :broom: Use newest magetasks (to include https://github.com/wavesoftware/go-magetasks/pull/35)

/kind cleanup

Fixes #243

### CODE REVIEW

**Comment by cardil** [comment]
/test integration-tests

The `InClusterSender/KnativeService` is flaky :crying_cat_face: https://github.com/knative-sandbox/kn-plugin-event/issues/242

**Comment by cardil** [comment]
/test integration-tests
 
> The `InClusterSender/KnativeService` is flaky crying_cat_face #242

**Comment by cardil** [comment]
/test integration-tests

> The InClusterSender/KnativeService is flaky :crying_cat_face: https://github.com/knative-sandbox/kn-plugin-event/issues/242

**Comment by cardil** [comment]
/test integration-tests

> The InClusterSender/KnativeService is flaky :crying_cat_face: https://github.com/knative-sandbox/kn-plugin-event/issues/242

**Comment by cardil** [comment]
/test integration-tests

> The InClusterSender/KnativeService is flaky :crying_cat_face: https://github.com/knative-sandbox/kn-plugin-event/issues/242

**Comment by cardil** [comment]
/test integration-tests

> The InClusterSender/KnativeService is flaky :crying_cat_face: https://github.com/knative-sandbox/kn-plugin-event/issues/242

**Comment by cardil** [comment]
/test integration-tests

> The InClusterSender/KnativeService is flaky :crying_cat_face: https://github.com/knative-sandbox/kn-plugin-event/issues/242

**Comment by cardil** [comment]
/test integration-tests

> The InClusterSender/KnativeService is flaky :crying_cat_face: https://github.com/knative-sandbox/kn-plugin-event/issues/242

This is awful... :sob:

**Comment by cardil** [comment]
@dsimansk can you approve once more?

The failures were caused by lack of 9cce8a1, not the flakiness (#242). I didn't notice that earlier. The flakiness is still there, but not as persistent.

**Review by rhuss — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
