### PR TITLE
:bug: Always send to cluster local Ksvc, when using in-cluster-sender

### LINKED ISSUE #145: Can't send event to non-cluster local ksvc when HTTPS route configured for Serving
Currently, the kn-event while sending event with _in-cluster-sender_, resolves knative service _URL_ to be the same as seen by end-user (address from `.Status.URL` field of _CR_).

When Serving using _HTTPS_ as default route template, and the certs are not globally trusted, the _in-cluster-sender_ fails to connect to the service.

One possible solution would be to always send events to cluster local address of Knative service, as Eventing is apparently doing. Although, I don't know if the Knative service has a contract that cluster local endpoint be always available.

Other option would be to implement something described in #31 

/kind bug

### PR DESCRIPTION
**Pull request by cardil**
# Changes

- :bug: Always send to cluster local Ksvc, when using in-cluster-sender

/kind bug

Fixes #145

### CODE REVIEW

**Comment by cardil** [comment]
/hold

Waiting for decision on how to fix #145

**Comment by cardil** [comment]
Based on [slack discussion](https://knative.slack.com/archives/C93E33SN8/p1642608446066200) and  https://github.com/knative/serving/issues/12533 I think it's safe to assume that for now we should align with Eventing, and just use URI returned from address resolver. That's exactly what this PR is doing.

/unhold

**Comment by rhuss** [comment]
thanks !

/approve
/lgtm

**Pull request merged**
