### PR TITLE
:wastebasket: Migrate to `wavesoftware/commandline` package

### LINKED ISSUE #181: Move the `retcode` package to an external dependency
https://github.com/knative-sandbox/kn-plugin-event/blob/12c41b218251257b5b4174de95472adaf8e8e935/pkg/cli/retcode/retcode.go#L5-L11

Move the `retcode` package to `knative.dev/pkg` or other external dependency

### PR DESCRIPTION
**Pull request by cardil**
# Changes

- :wastebasket: Migrate to [wavesoftware/commandline](https://pkg.go.dev/github.com/wavesoftware/go-commandline) package

/kind cleanup

Fixes #181

### CODE REVIEW

**Comment by cardil** [comment]
/test integration-tests_kn-plugin-event_main

Flake?

**Comment by dsimansk** [comment]
IMO looks good, I wonder if that common code could live in `knative/client-pkg` maybe. We'd like to revive that from the dusts. Otherwise it looks good, feel free to unhold.

/approve
/lgtm
/hold

**Comment by cardil** [comment]
> _I wonder if that common code could live in `knative/client-pkg` maybe_

I'm using that [`commandline` package](https://pkg.go.dev/github.com/wavesoftware/go-commandline) in knative/test-infra tools now. See knative/test-infra#3513 and https://github.com/knative/test-infra/pull/2995. I think it's not a good idea to import `knative/client-pkg` from `knative/test-infra`.

**Comment by cardil** [comment]
I'm also using that [`commandline` package](https://pkg.go.dev/github.com/wavesoftware/go-commandline) in https://github.com/knative/hack/pull/222

**Pull request merged**
